import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { Prisma, Product, ProductVariant } from '@prisma/client';
import sanitizeHtml from 'sanitize-html';
import { apiEntity } from '../../common/utils/api-entity';
import { PrismaService } from '../../database/prisma.service';
import { SettingsService } from '../settings/settings.service';
import { TelegramService } from '../telegram/telegram.service';
import { CreateProductDto } from './dto/create-product.dto';
import { UpdateProductDto } from './dto/update-product.dto';
import { ProductVariantStockDto } from './dto/update-product-stock.dto';

const includeProduct = { category: true, variants: true, relatedProducts: { include: { category: true, variants: true } } } as const;
type FullProduct = Prisma.ProductGetPayload<{ include: typeof includeProduct }>;
@Injectable()
export class ProductsService {
  constructor(private readonly prisma:PrismaService,private readonly settings:SettingsService,private readonly telegram:TelegramService,private readonly config:ConfigService){}
  private mapRelated(row:any){return{...apiEntity(row),category:row.category?apiEntity(row.category):row.category,variants:(row.variants??[]).map((v:any)=>({...apiEntity(v),color:v.color||undefined,size:v.size||undefined}))};}
  private map(row:FullProduct|any){return{...this.mapRelated(row),relatedProducts:(row.relatedProducts??[]).map((p:any)=>this.mapRelated(p))};}
  private sanitize(html?:string){if(!html)return'';const clean=sanitizeHtml(html,{allowedTags:['h1','h2','h3','h4','div','span','p','strong','em','u','s','ul','ol','li','blockquote','br','hr','a'],allowedAttributes:{a:['href','target','rel'],'*':['class','style']},allowedClasses:{'*':['ql-align-center','ql-align-right','ql-align-justify']},allowedStyles:{'*':{'text-align':[/^left$/, /^right$/, /^center$/, /^justify$/],'font-size':[/^\d+(?:px|pt|em|rem|%)$/]}},allowedSchemes:['http','https','mailto']});return sanitizeHtml(clean,{allowedTags:[],allowedAttributes:{}}).replace(/\s+/g,' ').trim()?clean:'';}
  private async requireCategory(id:string){if(!await this.prisma.category.findUnique({where:{id}}))throw new BadRequestException('Category not found');}
  private async assertRelated(ids?:string[]){if(!ids?.length)return;const unique=[...new Set(ids)];if(await this.prisma.product.count({where:{id:{in:unique}}})!==unique.length)throw new BadRequestException('One or more related products do not exist');}
  private async descendants(id:string){const ids=[id];let parents=[id];while(parents.length){const rows=await this.prisma.category.findMany({where:{parentId:{in:parents}},select:{id:true}});parents=rows.map(r=>r.id);ids.push(...parents)}return ids;}
  private adminUrl(id:string){return `${this.config.get<string>('adminPanelUrl')??'http://127.0.0.1:5173'}/products?highlight=${id}`;}
  private async notify(row:Product&{variants:ProductVariant[]}){if(row.variants.length){for(const v of row.variants){const should=v.lowStockThreshold!==null&&v.stock<=v.lowStockThreshold;if(should&&!v.lowStockNotified){await this.telegram.sendMessage(['نوع اعلان: موجودی کم تنوع محصول',`کالا: ${row.name}`,`تنوع: ${[v.color,v.size].filter(Boolean).join(' / ')||'پیش‌فرض'}`,`موجودی فعلی: ${v.stock} — آستانه: ${v.lowStockThreshold}`,`دسترسی: ${this.adminUrl(row.id)}`].join('\n'));await this.prisma.productVariant.update({where:{id:v.id},data:{lowStockNotified:true}})}else if(!should&&v.lowStockNotified)await this.prisma.productVariant.update({where:{id:v.id},data:{lowStockNotified:false}})}return;}const should=row.lowStockThreshold!==null&&row.stock<=row.lowStockThreshold;if(should&&!row.lowStockNotified){await this.telegram.sendMessage(['نوع اعلان: موجودی کم',`کالا: ${row.name}`,`دسترسی: ${this.adminUrl(row.id)}`,`موجودی فعلی: ${row.stock} — آستانه: ${row.lowStockThreshold}`].join('\n'));await this.prisma.product.update({where:{id:row.id},data:{lowStockNotified:true}})}else if(!should&&row.lowStockNotified)await this.prisma.product.update({where:{id:row.id},data:{lowStockNotified:false}});}
  async create(dto:CreateProductDto){await this.requireCategory(dto.category);await this.assertRelated(dto.relatedProducts);const shipping=dto.shippingCost??await this.settings.getDefaultShippingCost();const row=await this.prisma.product.create({data:{name:dto.name,description:dto.description,descriptionHtml:this.sanitize(dto.descriptionHtml),price:dto.price??0,discountPercent:dto.discountPercent??0,shippingCost:shipping,images:dto.images??[],categoryId:dto.category,stock:dto.stock??0,colors:(dto.colors??[]) as Prisma.InputJsonValue,sizeType:dto.sizeType??'letter',sizes:(dto.sizes??[]) as Prisma.InputJsonValue,lowStockThreshold:dto.lowStockThreshold??null,isActive:dto.isActive??true,attributes:(dto.attributes??{}) as Prisma.InputJsonValue,relatedProducts:{connect:[...new Set(dto.relatedProducts??[])].map(id=>({id}))}},include:includeProduct});await this.notify(row);return this.findById(row.id);}
  async findAll(page=1,limit=20,filters?:{category?:string;search?:string;onlyActive?:boolean;minPrice?:number;maxPrice?:number;inStock?:boolean}){const base:Prisma.ProductWhereInput={...(filters?.category?{categoryId:{in:await this.descendants(filters.category)}}:{}),...(filters?.onlyActive?{isActive:true}:{}),...(filters?.search?{OR:[{name:{contains:filters.search,mode:'insensitive'}},{description:{contains:filters.search,mode:'insensitive'}}]}:{}),...(filters?.inStock?{stock:{gt:0}}:{})};const where={...base,...(filters?.minPrice!==undefined||filters?.maxPrice!==undefined?{price:{gte:filters.minPrice,lte:filters.maxPrice}}:{})};const[rows,total,range]=await Promise.all([this.prisma.product.findMany({where,include:includeProduct,skip:(page-1)*limit,take:limit,orderBy:{createdAt:'desc'}}),this.prisma.product.count({where}),this.prisma.product.aggregate({where:base,_min:{price:true},_max:{price:true}})]);return{items:rows.map(r=>this.map(r)),meta:{total,page,limit,totalPages:Math.ceil(total/limit)||1,priceRange:{min:range._min.price??0,max:range._max.price??0}}};}
  async findById(id:string){const row=await this.prisma.product.findUnique({where:{id},include:includeProduct});if(!row)throw new NotFoundException('Product not found');return this.map(row);}
  async findActiveById(id:string){const row=await this.prisma.product.findFirst({where:{id,isActive:true},include:includeProduct});if(!row)throw new NotFoundException('Product not found');row.relatedProducts=row.relatedProducts.filter(p=>p.isActive);return this.map(row);}
  async update(id:string,dto:UpdateProductDto){const current=await this.prisma.product.findUnique({where:{id}});if(!current)throw new NotFoundException('Product not found');if(dto.category)await this.requireCategory(dto.category);if(dto.relatedProducts?.includes(id))throw new BadRequestException('A product cannot be related to itself');await this.assertRelated(dto.relatedProducts);const data:Prisma.ProductUpdateInput={name:dto.name,description:dto.description,descriptionHtml:dto.descriptionHtml===undefined?undefined:this.sanitize(dto.descriptionHtml),shippingCost:dto.shippingCost,discountPercent:dto.discountPercent,images:dto.images,category:dto.category?{connect:{id:dto.category}}:undefined,colors:dto.colors as Prisma.InputJsonValue|undefined,sizeType:dto.sizeType,sizes:dto.sizes as Prisma.InputJsonValue|undefined,lowStockThreshold:dto.lowStockThreshold,isActive:dto.isActive,attributes:dto.attributes as Prisma.InputJsonValue|undefined,relatedProducts:dto.relatedProducts?{set:[...new Set(dto.relatedProducts)].map(x=>({id:x}))}:undefined};const row=await this.prisma.product.update({where:{id},data,include:{variants:true}});await this.notify(row);return this.findById(id);}
  async remove(id:string){try{await this.prisma.product.delete({where:{id}})}catch{throw new NotFoundException('Product not found')}}
  async updatePrice(id:string,price:number){try{await this.prisma.product.update({where:{id},data:{price}})}catch{throw new NotFoundException('Product not found')}return this.findById(id);}
  async setStock(id:string,stock:number,lowStockThreshold?:number|null){const row=await this.prisma.product.update({where:{id},data:{stock,...(lowStockThreshold!==undefined?{lowStockThreshold}:{})},include:{variants:true}}).catch(()=>{throw new NotFoundException('Product not found')});await this.notify(row);return this.findById(id);}
  async setVariants(id:string,variants:ProductVariantStockDto[]){const product=await this.prisma.product.findUnique({where:{id}});if(!product)throw new NotFoundException('Product not found');const colors=product.colors as Array<{name:string}>;const sizes=product.sizes as Array<{label:string}>;const seen=new Set<string>();for(const v of variants){const key=`${v.color??''}::${v.size??''}`;if(seen.has(key))throw new BadRequestException('ترکیب رنگ و سایز تکراری است');seen.add(key);if(colors.length&&!v.color)throw new BadRequestException('رنگ همه تنوع‌ها باید مشخص باشد');if(v.color&&!colors.some(c=>c.name===v.color))throw new BadRequestException(`رنگ «${v.color}» معتبر نیست`);if(sizes.length&&!v.size)throw new BadRequestException('سایز همه تنوع‌ها باید مشخص باشد');if(v.size&&!sizes.some(s=>s.label===v.size))throw new BadRequestException(`سایز «${v.size}» معتبر نیست`)}const stock=variants.reduce((s,v)=>s+v.stock,0);await this.prisma.$transaction([this.prisma.productVariant.deleteMany({where:{productId:id}}),this.prisma.productVariant.createMany({data:variants.map(v=>({productId:id,color:v.color??'',size:v.size??'',stock:v.stock,lowStockThreshold:v.lowStockThreshold??null}))}),this.prisma.product.update({where:{id},data:{stock}})]);const row=await this.prisma.product.findUniqueOrThrow({where:{id},include:{variants:true}});await this.notify(row);return this.findById(id);}
  async adjustStock(id:string,delta:number,selection?:{color?:string;size?:string}){const row=await this.prisma.$transaction(async tx=>{const product=await tx.product.findUnique({where:{id},include:{variants:true}});if(!product)throw new NotFoundException('Product not found');if(product.variants.length){const variant=product.variants.find(v=>v.color===(selection?.color??'')&&v.size===(selection?.size??''));if(!variant)throw new BadRequestException('تنوع انتخاب‌شده برای محصول پیدا نشد');if(variant.stock+delta<0)throw new BadRequestException('موجودی این رنگ و سایز کافی نیست');await tx.productVariant.update({where:{id:variant.id},data:{stock:{increment:delta}}});return tx.product.update({where:{id},data:{stock:{increment:delta}},include:{variants:true}})}if(product.stock+delta<0)throw new BadRequestException('Insufficient stock');return tx.product.update({where:{id},data:{stock:{increment:delta}},include:{variants:true}})});await this.notify(row);return this.findById(id);}
}
