import { BadRequestException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { OrderStatus as DbOrderStatus, PaymentMethod as DbPaymentMethod, PaymentStatus as DbPaymentStatus, Prisma } from '@prisma/client';
import { OrderStatus,PaymentMethod,PaymentStatus } from '../../common/enums/order.enum';
import { apiEntity } from '../../common/utils/api-entity';
import { PrismaService } from '../../database/prisma.service';
import { CartService } from '../cart/cart.service';
import { ProductsService } from '../products/products.service';
import { CheckoutDto } from './dto/checkout.dto';
import { UpdateOrderStatusDto,UpdatePaymentStatusDto } from './dto/update-order.dto';
const includeOrder={user:{select:{id:true,email:true,firstName:true,lastName:true,phone:true}},items:true} as const;
@Injectable()
export class OrdersService {
  constructor(private readonly prisma:PrismaService,private readonly products:ProductsService,private readonly cart:CartService){}
  private number(){return`ORD-${Date.now().toString(36).toUpperCase()}-${Math.random().toString(36).slice(2,6).toUpperCase()}`;}
  private map(row:any){return{...apiEntity(row),user:apiEntity(row.user),items:row.items.map((i:any)=>({...apiEntity(i),product:i.productId}))};}
  async checkout(userId:string,dto:CheckoutDto){const cart=await this.cart.getCartDocument(userId);if(!cart.items.length)throw new BadRequestException('Cart is empty');let subtotal=0;for(const item of cart.items){const p=item.product;const v=p.variants.length?p.variants.find(x=>x.color===item.color&&x.size===item.size):undefined;if(!p.isActive)throw new BadRequestException(`Product ${p.id} is unavailable`);if(p.variants.length&&!v)throw new BadRequestException(`Selected variant for "${p.name}" is unavailable`);const stock=v?.stock??p.stock;if(stock<item.quantity)throw new BadRequestException(`Insufficient stock for "${p.name}". Available: ${stock}`);subtotal+=p.price*item.quantity}for(const i of cart.items)await this.products.adjustStock(i.productId,-i.quantity,{color:i.color||undefined,size:i.size||undefined});const shippingCost=dto.shippingCost??0;const order=await this.prisma.order.create({data:{orderNumber:this.number(),userId,status:'pending',shippingAddress:dto.shippingAddress as Prisma.InputJsonValue,paymentStatus:'pending',paymentMethod:(dto.paymentMethod??PaymentMethod.CASH_ON_DELIVERY) as DbPaymentMethod,subtotal,shippingCost,totalAmount:subtotal+shippingCost,notes:dto.notes,items:{create:cart.items.map(i=>({productId:i.productId,name:i.product.name,price:i.product.price,quantity:i.quantity,image:i.product.images[0],color:i.color||undefined,size:i.size||undefined}))}},include:includeOrder});await this.cart.clearCart(userId);return this.map(order);}
  private where(filters?:{status?:OrderStatus;paymentStatus?:PaymentStatus;userId?:string;search?:string}):Prisma.OrderWhereInput{return{...(filters?.status?{status:filters.status as DbOrderStatus}:{}),...(filters?.paymentStatus?{paymentStatus:filters.paymentStatus as DbPaymentStatus}:{}),...(filters?.userId?{userId:filters.userId}:{}),...(filters?.search?{orderNumber:{contains:filters.search,mode:'insensitive'}}:{})};}
  async findAll(page=1,limit=20,filters?:{status?:OrderStatus;paymentStatus?:PaymentStatus;userId?:string;search?:string}){const where=this.where(filters);const[rows,total]=await Promise.all([this.prisma.order.findMany({where,include:includeOrder,skip:(page-1)*limit,take:limit,orderBy:{createdAt:'desc'}}),this.prisma.order.count({where})]);return{items:rows.map(r=>this.map(r)),meta:{total,page,limit,totalPages:Math.ceil(total/limit)||1}};}
  async getStats(){const[statuses,payments,revenue,totalOrders]=await Promise.all([this.prisma.order.groupBy({by:['status'],_count:true}),this.prisma.order.groupBy({by:['paymentStatus'],_count:true}),this.prisma.order.aggregate({where:{status:{not:'cancelled'},paymentStatus:'paid'},_sum:{totalAmount:true},_count:true}),this.prisma.order.count()]);const byStatus=Object.fromEntries(Object.values(OrderStatus).map(s=>[s,statuses.find(x=>x.status===s)?._count??0]));const byPaymentStatus=Object.fromEntries(Object.values(PaymentStatus).map(s=>[s,payments.find(x=>x.paymentStatus===s)?._count??0]));return{totalOrders,byStatus,byPaymentStatus,paidRevenue:revenue._sum.totalAmount??0,paidOrders:revenue._count};}
  findByUser(userId:string,page=1,limit=20){return this.findAll(page,limit,{userId});}
  async findById(id:string){const row=await this.prisma.order.findUnique({where:{id},include:includeOrder});if(!row)throw new NotFoundException('Order not found');return this.map(row);}
  async findByIdForUser(id:string,userId:string){const row=await this.findById(id);if(row.user.id!==userId)throw new ForbiddenException('You cannot access this order');return row;}
  async cancelByCustomer(id:string,userId:string){const row=await this.findByIdForUser(id,userId);if(![OrderStatus.PENDING,OrderStatus.CONFIRMED].includes(row.status))throw new BadRequestException('Only pending or confirmed orders can be cancelled');return this.updateStatus(id,{status:OrderStatus.CANCELLED});}
  async updateStatus(id:string,dto:UpdateOrderStatusDto){const row=await this.findById(id);if(row.status===OrderStatus.CANCELLED)throw new BadRequestException('Cancelled order cannot be updated');if(dto.status===OrderStatus.CANCELLED)for(const item of row.items)await this.products.adjustStock(item.productId,item.quantity,{color:item.color,size:item.size});await this.prisma.order.update({where:{id},data:{status:dto.status as DbOrderStatus,notes:dto.notes,deliveredAt:dto.status===OrderStatus.DELIVERED?new Date():row.status===OrderStatus.DELIVERED?null:undefined,cancelledAt:dto.status===OrderStatus.CANCELLED?new Date():undefined,paymentStatus:dto.status===OrderStatus.DELIVERED&&row.paymentStatus===PaymentStatus.PENDING?'paid':undefined}});return this.findById(id);}
  async updatePaymentStatus(id:string,dto:UpdatePaymentStatusDto){await this.findById(id);await this.prisma.order.update({where:{id},data:{paymentStatus:dto.paymentStatus as DbPaymentStatus}});return this.findById(id);}
}
