services:
  mongo:
    image: mongo:7
    container_name: shop-mongo
    ports:
      - '27017:27017'
    volumes:
      - shop_mongo_data:/data/db
    restart: unless-stopped

volumes:
  shop_mongo_data:
