"use client";
import { useState } from "react";
import { toast } from "react-toastify";
import { getProfile, loginCustomer, registerCustomer, updateProfile } from "@core/services/api/auth.api";
import { useAuthStore } from "@core/services/stores/auth.store";
export function ProfilePanel() {
  const user = useAuthStore((state) => state.user); const setAuth = useAuthStore((state) => state.setAuth); const setUser = useAuthStore((state) => state.setUser); const logout = useAuthStore((state) => state.logout);
  const [mode, setMode] = useState<"login" | "register">("login"); const [form, setForm] = useState({ firstName: "", lastName: "", phone: "", password: "" });
  const submit = async (event: React.FormEvent) => { event.preventDefault(); try { const data = mode === "login" ? await loginCustomer(form.phone, form.password) : await registerCustomer(form); setAuth(data.accessToken, data.user); toast.success("با موفقیت وارد شدید") } catch { toast.error("اطلاعات ورود صحیح نیست یا شماره همراه قبلاً ثبت شده است") } };
  const save = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget)); try { const updated = await updateProfile(values); setUser(updated); toast.success("پروفایل ذخیره شد") } catch { toast.error("ذخیره پروفایل انجام نشد") } };
  if (!user) return <div className="auth-card"><div className="auth-tabs"><button className={mode === "login" ? "active" : ""} onClick={() => setMode("login")}>ورود</button><button className={mode === "register" ? "active" : ""} onClick={() => setMode("register")}>ثبت‌نام</button></div><form onSubmit={submit}>{mode === "register" ? <><label>نام<input value={form.firstName} onChange={(e) => setForm({ ...form, firstName: e.target.value })}/></label><label>نام خانوادگی<input value={form.lastName} onChange={(e) => setForm({ ...form, lastName: e.target.value })}/></label></> : null}<label>شماره همراه<input dir="ltr" inputMode="tel" value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} placeholder="09121234567"/></label><label>رمز عبور<input type="password" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })}/></label><button className="primary-btn">{mode === "login" ? "ورود به حساب" : "ساخت حساب"}</button><small>ورود پیامکی در مرحله اتصال سرویس پیامک جایگزین این بخش می‌شود.</small></form></div>;
  return <div className="profile-grid"><aside><span>حساب Oner</span><b>{user.firstName} {user.lastName}</b><small>{user.phone}</small><button onClick={logout}>خروج از حساب</button></aside><form className="profile-form" onSubmit={save}><h2>اطلاعات شخصی</h2><label>نام<input name="firstName" defaultValue={user.firstName}/></label><label>نام خانوادگی<input name="lastName" defaultValue={user.lastName}/></label><label>شماره همراه<input name="phone" dir="ltr" defaultValue={user.phone}/></label><button className="primary-btn">ذخیره تغییرات</button></form></div>;
}
